spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chaptgen
    username: chaptgen
    password: chaptgen
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration